export const FACEBOOK_URL = 'https://www.facebook.com/BalanceBreaker1112/'
export const LINKEDIN_URL = 'https://www.linkedin.com/in/giangbui111299/'
export const GITHUB_URL = 'https://github.com/arthurleywin99'
export const CONTACT_EMAIL = 'buinguyentruonggiang.1112@gmail.com'
export const CONTRACT_TELEPHONE = '+84 354321 915'
